### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by lordnn** [neoml-lib/neoml#17]
Why do you use both keywords 'virtual' and 'override' in methods definition? It's redundantly and hard to read, because semantics for this keywords are different.

**Comment by m1t0z** [comment]
@lordnn, thank you very much for the given feedback. 

I totally agree with your remark. C++ core guidelines also say that declaration of the virtual function should contain only one of the following keywords: 'virtual', 'override', 'final'. [C128](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final).

Our team will defiantly add this issue to the backlog, but due to the current work load we cannot promise to address it soon.

Alternatively anyone outside of our team can make a PR to fix the issue. We would be happy for any contribution from the community.

**Comment by ZigRazor** [comment]
@m1t0z  I could try to solve this code style issue. 

A pull request will come soon

**Comment by ZigRazor** [comment]
Sorry for the 2 PR closed, but forgot the sign in the commit.

**Comment by lordnn** [comment]
That's not all:
CCrossValidationSubProblem::GetOriginalIndex,
CStratifiedCrossValidationSubProblem::GetOriginalIndex,
and CClassificationStatistics all methods must be marked with an 'override' specifier.

**Comment by ZigRazor** [comment]
@lordnn 
i think this could be another issue to resolve.

**Comment by lordnn** [comment]
Absolutely! Especially if you get paid for the number of closed issues. :-)

**Comment by FedyuninV** [comment]
#25 merged. If there are some other wishes about syntax, we can reopen this later (or open new issue).
