### ISSUE TITLE
[Feature] Add flutter bindings

### ISSUE THREAD

**Issue by shigomany** [neoml-lib/neoml#515]

**Comment by FedyuninV** [comment]
Can you explain more please? I'm not familiar with flutter at all.

**Comment by shigomany** [comment]
[Flutter](https://flutter.dev/) is a multiplatform framework for development for Mobile (android, iOS, fuchsia in the future), Desktop (Linux, Windows, macOS), Web, Embedded. He is very much gaining popularity. It is mainly used for Android and iOS development. Now it has poorly developed neural networks. Since you already have integration with Java, Objective C, it would be possible to make a library on [pub.dev](https://pub.dev/), which will make a good contribution to the development of the framework (as well as give you a great popularity of your library. Integration of flutter and the native part occurs by [PlatformChannel](https://docs.flutter.dev/development/platform-integration/platform-channels)

Now there are poorly developed libraries:

- https://pub.dev/packages/tflite
- https://pub.dev/packages/google_ml_vision

Moreover, all libraries are about third-party developers

**Comment by shigomany** [comment]
@FedyuninV What think about it?

**Comment by FedyuninV** [comment]
@ltropin as an idea it looks interesting, but AFAIK none of my colleagues is familiar with Flutter and Dart (myself included). And right now we have our hands full with some other tasks (optimizations + moving towards distributed training). That's why I can't guarantee that we're going to implement this, but I'll discuss it with others after the holidays.

I'm leaving this issue open as a remainder.

**Comment by FedyuninV** [comment]
@ltropin currently we don't have the need for these bindings on our side, that's why we're not going to implement it in near future. That doesn't prevent you from implementing them on your side (if needed).
